update the yml

diff --git a/.github/workflows/manual.yml b/.github/workflows/manual.yml
--- a/.github/workflows/manual.yml
+++ b/.github/workflows/manual.yml
@@ -1,31 +1,42 @@
-name: Python application test with Github Actions
+name: CI/CD Pipeline
 
 on:
   push:
-    branches: [ "main", "master" ]
+    branches: [ main, master ]
   pull_request:
-    branches: [ "main", "master" ]
+    branches: [ main, master ]
 
 jobs:
-  build:
+  test:
     runs-on: ubuntu-latest
     steps:
     - uses: actions/checkout@v2
-    - name: Set up Python 3.8
+    - name: Set up Python
       uses: actions/setup-python@v2
       with:
-        python-version: 3.8
+        python-version: '3.8'
     - name: Install dependencies
       run: |
         python -m pip install --upgrade pip
+        pip install -r starter/requirements.txt
         pip install flake8 pytest
-        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
-    - name: Lint with flake8
+    - name: Run flake8
       run: |
-        # stop the build if there are Python syntax errors or undefined names
-        flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
-        # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
-        flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
-    - name: Test with pytest
+        cd starter
+        flake8 .
+    - name: Start FastAPI application
       run: |
-        pytest
+        cd starter
+        uvicorn main:app --host 0.0.0.0 --port 8000 &
+        sleep 5  # Give the server some time to start
+    - name: Run tests
+      run: |
+        cd starter
+        pytest test_model_and_api.py -v
+    - name: Check test count
+      run: |
+        test_count=$(pytest starter/test_model_and_api.py --collect-only -q | tail -n 1 | cut -d: -f2)
+        if [ "$test_count" -lt 6 ]; then
+          echo "Error: There are fewer than 6 tests."
+          exit 1
+        fi
